DROP TABLE IF EXISTS `cbs_certification_types`;
CREATE TABLE IF NOT EXISTS `cbs_certification_types` (
  `iid` int(11) NOT NULL AUTO_INCREMENT,
  `iname` varchar(50) DEFAULT NULL,
  `comments` varchar(50) DEFAULT NULL,
  `amount` int(11) NOT NULL DEFAULT 0,
  `body_text` varchar(1024) NOT NULL DEFAULT '<insert text here>',
  `lgu_type_id` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`iid`),
  UNIQUE KEY `iname` (`iname`),
  KEY `lgu_type_id` (`lgu_type_id`),
  CONSTRAINT `cbs_certification_types_ibfk_1` FOREIGN KEY (`lgu_type_id`) REFERENCES `lgu_types` (`iid`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT INTO `cbs_certification_types` (`iid`, `iname`, `comments`, `amount`, `body_text`, `lgu_type_id`) VALUES
	(1, 'Assistance Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n\r\n	This is to certify that [APPLICANT_NAME], is a resident at [COMPLETE_ADDRESS] was affected by [CALAMITY_NAME] which occurred on [CALAMITY_DATE].\r\n	This certification is issued upon the request of the affected party for the purpose of claiming assistance related to the said disaster.\r\n    \r\n	Issued this [date] day of  [MONTH] [YEAR] at Barangay Colo, Dinalupihan Bataan.', 1),
	(2, 'Business Permit Certification', NULL, 0, '<insert text here>', 1),
	(3, 'Business Closure Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	I, [BARANGAY_CAPTAIN], Punong Barangay of the said area, certify that [BUSINESS_NAME], located at [ADDRESS], has ceased its operations and closed down effective [CLOSURE_DATE]. The aforementioned business has been inactive since the mentioned date and is currently not operating.\r\n\r\n	I also certify that the said establishment closed properly and complied with all barangay regulations without any issues.\r\n\r\n	This serves as my truthful record as Punong Barangay. \r\n	\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan, Bataan.\r\n ', 1),
	(4, 'Calamity Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n \r\n	This is to certify that [APPLICANT_NAME], a resident of Barangay Colo, was unable to report for work from [START_DATE] to [END_DATE] due to the severe rainfall & wind caused by [CALAMITY_NAME].\r\n	The said [CALAMITY_NAME] significantly affected the barangay, rendering many areas impassable and causing widespread disruption to daily activities. \r\n	This certification is issued upon the request of the concerned individual for whatever legal purpose it may serve.\r\n\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan, Bataan.\r\n\r\n', 1),
	(5, 'Death Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [DECEASED_NAME], [AGE] years of age, is a bonafide resident of this Barangay and was died on [DATE_OF_DEATH].\r\n	Further certifies that [DECEASED_NAME] was died in their residence at [ADDRESS].\r\n	This certification is issued to MR. [APPLICANT_NAME] for whatever legal purpose it may serve.\r\n    \r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan Bataan.\r\n\r\n', 1),
	(6, 'Indigency Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [RESIDENT_NAME], [CIVIL_STATUS], is a bonafide resident of Barangay Colo, Dinalupihan, Bataan.\r\n	This family, as per record of this office and the prevailing circumstances warranting their economics status, has no permanent source of income and that their means of living is below the poverty line.\r\n	I can attest to the fact that the said family is classified as indigent.\r\n	This certification is issued to [APPLICANT_NAME] for whatever legal purpose it may serve.\r\n\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan, Bataan.\r\n\r\n', 1),
	(7, 'Lot Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [APPLICANT_NAME], resident of, Colo Dinalupihan Bataan possessed a parcel of land situated at Centro Colo Dinalupihan, Bataan.\r\n\r\n	Consisting of [LOT_SIZE] more or less.\r\n\r\n	THIS CERTIFICATION was issued for [PURPOSE].\r\n\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan, Bataan.\r\n\r\n                         \r\n	Certified By:\r\n	[BARANGAY_CAPTAIN]\r\n	Punong Barangay\r\n\r\n	Attested By:\r\n	[BARANGAY_COUNCILOR]\r\n	[COMITTEE]\r\n\r\n	Noted By:\r\n	[BARANGAY_SECRETARY]\r\n	Barangay Secretary', 1),
	(8, 'Residence Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [APPLICANT_NAME] , [AGE] years old, [GENDER], whose picture appearing herein is a bonifide resident of Barangay Colo, Dinalupihan, Bataan. He/She was born in [BIRTH_PLACE], on [BIRTH_DATE] to parents [FATHERS_NAME] and [MOTHERS_NAME].\r\n\r\n	This certification is being issued to ________________ as requirements for registration of birth of __________________ at the Local Civil Registrar’s Office of Dinalupihan, Bataan.\r\n\r\n	Issued this [DATE] day of  [MONTH] [YEAR] at Barangay Colo, Dinalupihan Bataan.\r\n	\r\n', 1),
	(9, 'Relationship Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [APPLICANT_NAME] is a bonafide resident of [ADDRESS].\r\n	Further certifies that [APPLICANT_NAME] and [PARTNER_NAME] are living together as live-in partner since [YEAR].\r\n\r\n	This certification is issued for whatever legal purpose it may served.\r\n\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan, Bataan.\r\n\r\n', 1),
	(10, 'Requisition Certification', NULL, 0, '	Ako si [APPLICANT_NAME] ay humihingi ng ____________________. Ito ay aking gagamitin para sa _______________________________________________________.\r\n\r\n	Nais ko po sana na nailagay ang mga sumusunod sa aking hihiling na _______________________________________________________________________________________________________.\r\n	(kung special na certification ang hinihiling)\r\n\r\n\r\n	Maraming salamat po.', 1),
	(11, 'Solo Parent Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that MS. ELLAINE BEVERLY A. RONQUILLO , Single  and a bonafide resident of Liaban Colo Dinalupihan, Bataan.\r\n	Further certifies [APPLICANT_NAME], is a solo parent since [YEAR] and have [NO_OF_CHILD] dependent child namely:  \r\n		1. [CHILD_NAME] ([AGE] year old).\r\n\r\n	THIS CERTIFICATION is issued upon for whatever legal purpose it may serve.\r\n\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan Bataan.\r\n\r\n', 1),
	(12, 'PSA Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [APPLICANT_NAME] , [AGE] years old, [GENDER], whose picture appearing herein is a bonifide resident of Barangay Colo, Dinalupihan, Bataan. He/She was born in [BIRTH_PLACE], on [BIRTH_DATE] to parents [FATHERS_NAME] and [MOTHERS_NAME].\r\n\r\n	This certification is being issued to ________________ as requirements for registration of birth of __________________ at the Local Civil Registrar’s Office of Dinalupihan, Bataan.\r\n\r\n	Issued this [DATE] day of  [MONTH] [YEAR] at Barangay Colo, Dinalupihan Bataan.\r\n	\r\n', 1),
	(13, 'Unemployment Certification', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [APPLICANT_NAME], widowed is a bonafide resident of this Barangay and currently residing at [ADDRESS].\r\n	Further certifies that the above name was unemployed from the time that this certification was issued.\r\n\r\n	This certification is issued upon for whatever legal purpose it may serve.\r\n\r\n	Issued this [DATE] day of [MONTH] [YEAR] at Barangay Colo, Dinalupihan, Bataan.\r\n', 1),
	(14, 'RA 11261 Certification', NULL, 0, '<insert text here>', 1),
	(15, 'Electrical Permit', NULL, 0, '<insert text here>', 1),
	(16, 'Fencing Certification', NULL, 0, '<insert text here>', 1),
	(17, 'Barangay Clearance', NULL, 0, 'TO WHOM IT MAY CONCERN:\r\n\r\n	This is to certify that [APPLICANT_NAME], [AGE] years old, [CIVIL_STATUS, a resident of this Barangay COLO, whose signature, right hand thumb mark, Community tax certificate number appears below is personally known to me to be a person of good moral character, peaceful and law-abiding citizen of this community.\r\n\r\n	Issued upon request the above named person for whatever legal purpose (s) it may serve.\r\n', 1);
